/*
 * This file was generated by `tools/codegen/gen_block.py`.
 */

#include "block.h"

template <>
bool hasProperty<BlockProperty::Solid>(const BlockType blockType) {
  switch (blockType) {
  case BlockType::Air: return false;
  case BlockType::Grass: return true;
  }
}
    
template <>
bool hasProperty<BlockProperty::Fluid>(const BlockType blockType) {
  switch (blockType) {
  case BlockType::Air: return false;
  case BlockType::Grass: return false;
  }
}
    
template <>
bool hasProperty<BlockProperty::PartialCell>(const BlockType blockType) {
  switch (blockType) {
  case BlockType::Air: return false;
  case BlockType::Grass: return false;
  }
}
    
template <>
bool hasProperty<BlockProperty::Transparent>(const BlockType blockType) {
  switch (blockType) {
  case BlockType::Air: return true;
  case BlockType::Grass: return false;
  }
}
    