/*
 * This file was generated by `tools/codegen/gen_block.py`.
 */

#ifndef MC_LIB_BLOCK_H
#define MC_LIB_BLOCK_H

#include <GL/glew.h>

enum class BlockType: GLuint {
  Air = 0, 
  Grass = 1, 
};

enum class BlockProperty: GLuint {
  Solid = 0, 
  Fluid = 1, 
  PartialCell = 2, 
  Transparent = 3, 
};

template <BlockProperty> bool hasProperty(const BlockType type);

#endif // MC_LIB_BLOCK_H
